# Programming Assignment 2
* CSCI-4930/5930 ML Fall 2021  (Be sure to discard which section you are not enrolled)
* Author: Ashis Kumer Biswas (Replace my name with yours)

### Let's load the given dataset

In [112]:
import pandas as pd
# First load the dataset into pandas dataframe
full_dataset = pd.read_csv('dataset/baby-weights-dataset.csv',delimiter=',')
judge_dataset = pd.read_csv('dataset/judge-without-labels.csv',delimiter=',')

## Tasks for everyone (Tasks 1-17)

## TASK 1: 
Separate the full_dataset into two parts: X and y, where X denotes the input matrix containing only the input (i.e., independent explanatory) variables, and y denotes the target variable containing only the target values for exactly the same number of samples in the given full_dataset.

In [32]:
X = full_dataset.iloc[:,:-1]
Y = full_dataset.iloc[:,-1]
print(Y)

0         4.3750
1         6.9375
2         8.5000
3         8.5000
4         9.0000
           ...
101395    9.1250
101396    7.3750
101397    7.5000
101398    7.6250
101399    6.2500
Name: BWEIGHT, Length: 101400, dtype: float64

## TASK 2:
* Given X representing the input matrix from the full_dataset, y being the target vector (the rightmost column of the full_dataset), obtained from Task 1: 
* randomly split the (X,y) dataset into 75% for training and 25% for testing using the library function from the library [sklearn.model_selection](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html) . Please pass to the train_test_split function an additional argument random_state=45931.
* Store the 4 splits as X_train, X_test, y_train, y_test respectively.
* Save the ID column for X_train and X_test into ID_train and ID_test as list variable.
* Now, drop the ID columns from both X_train and X_test

In [33]:

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.25, random_state=45931)


#Save the ID column for X_train and X_test into ID_train and ID_test as list variable
ID_train = X_train.iloc[:,1].to_frame()
ID_test = X_test.iloc[:,1].to_frame()


#drop the ID columns from both X_train and X_test
X_train = X_train.drop('ID', axis=1)
X_test = X_test.drop('ID', axis=1)
X_train.info()
X_test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 76050 entries, 16961 to 28789
Data columns (total 35 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   SEX       76050 non-null  int64
 1   MARITAL   76050 non-null  int64
 2   FAGE      76050 non-null  int64
 3   GAINED    76049 non-null  float64
 4   VISITS    76050 non-null  int64
 5   MAGE      76050 non-null  int64
 6   FEDUC     76049 non-null  float64
 7   MEDUC     76050 non-null  int64
 8   TOTALP    76050 non-null  int64
 9   BDEAD     76050 non-null  int64
 10  TERMS     76050 non-null  int64
 11  LOUTCOME  76050 non-null  int64
 12  WEEKS     76049 non-null  float64
 13  RACEMOM   76050 non-null  int64
 14  RACEDAD   76050 non-null  int64
 15  HISPMOM   76050 non-null  object
 16  HISPDAD   76050 non-null  object
 17  CIGNUM    76049 non-null  float64
 18  DRINKNUM  76050 non-null  int64
 19  ANEMIA    76050 non-null  int64
 20  CARDIAC   76050 non-null  int64
 21  ACLUNG    76050 non-null  int64
 22  DIABETES  76050 non-null  int64
 23  HERPES    76050 non-null  int64
 24  HYDRAM    76049 non-null  float64
 25  HEMOGLOB  76050 non-null  int64
 26  HYPERCH   76050 non-null  int64
 27  HYPERPR   76050 non-null  int64
 28  ECLAMP    76050 non-null  int64
 29  CERVIX    76050 non-null  int64
 30  PINFANT   76050 non-null  int64
 31  PRETERM   76050 non-null  int64
 32  RENAL     76050 non-null  int64
 33  RHSEN     76050 non-null  int64
 34  UTERINE   76050 non-null  int64
dtypes: float64(5), int64(28), object(2)
memory usage: 20.9+ MB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 25350 entries, 40925 to 85343
Data columns (total 35 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   SEX       25350 non-null  int64
 1   MARITAL   25350 non-null  int64
 2   FAGE      25350 non-null  int64
 3   GAINED    25350 non-null  float64
 4   VISITS    25350 non-null  int64
 5   MAGE      25350 non-null  int64
 6   FEDUC     25350 non-null  float64
 7   MEDUC     25350 non-null  int64
 8   TOTALP    25350 non-null  int64
 9   BDEAD     25350 non-null  int64
 10  TERMS     25350 non-null  int64
 11  LOUTCOME  25350 non-null  int64
 12  WEEKS     25350 non-null  float64
 13  RACEMOM   25350 non-null  int64
 14  RACEDAD   25350 non-null  int64
 15  HISPMOM   25350 non-null  object
 16  HISPDAD   25350 non-null  object
 17  CIGNUM    25350 non-null  float64
 18  DRINKNUM  25350 non-null  int64
 19  ANEMIA    25350 non-null  int64
 20  CARDIAC   25350 non-null  int64
 21  ACLUNG    25350 non-null  int64
 22  DIABETES  25350 non-null  int64
 23  HERPES    25350 non-null  int64
 24  HYDRAM    25350 non-null  float64
 25  HEMOGLOB  25350 non-null  int64
 26  HYPERCH   25350 non-null  int64
 27  HYPERPR   25350 non-null  int64
 28  ECLAMP    25350 non-null  int64
 29  CERVIX    25350 non-null  int64
 30  PINFANT   25350 non-null  int64
 31  PRETERM   25350 non-null  int64
 32  RENAL     25350 non-null  int64
 33  RHSEN     25350 non-null  int64
 34  UTERINE   25350 non-null  int64
dtypes: float64(5), int64(28), object(2)
memory usage: 7.0+ MB

## TASK 3:
Compute mean, stdev, min, max, 25% percentile, median and 75% percentile of BWEIGHT target variable (i.e, the target y) in the training set (i.e., y_train), and print the computed values as a numpy array containing these 7 results (respectively).

In [34]:
print('BWEIGHT Mean : ',round(y_train.to_frame()['BWEIGHT'].mean(),3))
print('BWEIGHT Standard Deviation : ',round(y_train.to_frame()['BWEIGHT'].std()))
print('BWEIGHT Minimum : ',round(y_train.to_frame()['BWEIGHT'].min()))
print('BWEIGHT Maximum : ',round(y_train.to_frame()['BWEIGHT'].max()))
print('BWEIGHT 25% Percentile : ',round(y_train.to_frame()['BWEIGHT'].quantile(0.25)))
print('BWEIGHT Median : ',round(y_train.to_frame()['BWEIGHT'].median()))
print('BWEIGHT 75% Percentile : ',round(y_train.to_frame()['BWEIGHT'].quantile(0.75)))

BWEIGHT Mean :  7.257
BWEIGHT Standard Deviation :  1
BWEIGHT Minimum :  0
BWEIGHT Maximum :  13
BWEIGHT 25% Percentile :  7
BWEIGHT Median :  7
BWEIGHT 75% Percentile :  8

## TASK 4: 
Given the training dataset (X_train, y_train), save as X_train_ohe after replacing all the non-numeric variables (i.e., categorical variables) with numeric encoding. Please consider using the "One-hot encoding" scheme i.e., introducing dummy variables. A brief description of the scheme can be found in the [DUMMY-variables.note.txt](DUMMY-variables.note.txt) file
* Use the same encoder to perform onehotencoding on the X_test dataset and save the result as X_test_ohe.
* Print the column names of X_test_ohe.

In [35]:
# Categorical boolean mask
categorical_feature_mask = X_train.dtypes==object
# filter categorical columns using mask and turn it into a list
categorical_cols = X_train.columns[categorical_feature_mask].tolist()
cat_columns_idx = [X_train.columns.get_loc(col) 
                   for col in categorical_cols]

In [36]:

from sklearn.compose import make_column_transformer
from sklearn.preprocessing import OneHotEncoder
column_trans = make_column_transformer(
    (OneHotEncoder(), categorical_cols),
    remainder='passthrough')

In [37]:
X_train_ohe = pd.DataFrame(column_trans.fit_transform(X_train),columns=column_trans.get_feature_names())

In [38]:
X_test_ohe = pd.DataFrame(column_trans.transform(X_test),columns=column_trans.get_feature_names())

In [39]:

X_test_ohe.columns

Index(['onehotencoder__x0_C', 'onehotencoder__x0_M', 'onehotencoder__x0_N',
       'onehotencoder__x0_O', 'onehotencoder__x0_P', 'onehotencoder__x0_S',
       'onehotencoder__x0_U', 'onehotencoder__x1_C', 'onehotencoder__x1_M',
       'onehotencoder__x1_N', 'onehotencoder__x1_O', 'onehotencoder__x1_P',
       'onehotencoder__x1_S', 'onehotencoder__x1_U', 'SEX', 'MARITAL', 'FAGE',
       'GAINED', 'VISITS', 'MAGE', 'FEDUC', 'MEDUC', 'TOTALP', 'BDEAD',
       'TERMS', 'LOUTCOME', 'WEEKS', 'RACEMOM', 'RACEDAD', 'CIGNUM',
       'DRINKNUM', 'ANEMIA', 'CARDIAC', 'ACLUNG', 'DIABETES', 'HERPES',
       'HYDRAM', 'HEMOGLOB', 'HYPERCH', 'HYPERPR', 'ECLAMP', 'CERVIX',
       'PINFANT', 'PRETERM', 'RENAL', 'RHSEN', 'UTERINE'],
      dtype='object')

## TASK 5: 
* Given the X_train_ohe (Onehot encoded Pandas Dataframe from Task 4), check if there are missing values, and if yes, count how many, and impute the missing values with corresponding mean values. 
* Finally, print the counting result as a Pandas dataframe named "missing_counts" having 2 columns {variable_name,num_of_missing_values).  Please make sure that the result lists all the input variables in the given dataset. 
* Now, impute the missing values by mean of the respective variable and save the revised dataframe as X_train_ohe_imputed.

In [40]:

variable_name_list = []
num_of_missing_values_list = []
for i in X_train_ohe.columns:
    variable_name_list.append(i)
    num_of_missing_values_list.append(X_train_ohe[i].isna().sum())   

missing_counts_dict = {'variable_name':variable_name_list, 'num_of_missing_values':num_of_missing_values_list}
missing_count = pd.DataFrame(missing_counts_dict)
#missing_count.info()

print('missing count dataframe : ')
print(missing_count.head(47))


X_train_ohe_imputed  = X_train_ohe.copy()
for i in X_train_ohe_imputed.columns:
    mean_val = X_train_ohe_imputed[i].mean()
    X_train_ohe_imputed[i].fillna(value=mean_val, inplace=True)
    
print('')
print('X_train_ohe_imputed dataframe : ')
X_train_ohe_imputed.isna().sum()

missing count dataframe :
          variable_name  num_of_missing_values
0   onehotencoder__x0_C                      0
1   onehotencoder__x0_M                      0
2   onehotencoder__x0_N                      0
3   onehotencoder__x0_O                      0
4   onehotencoder__x0_P                      0
5   onehotencoder__x0_S                      0
6   onehotencoder__x0_U                      0
7   onehotencoder__x1_C                      0
8   onehotencoder__x1_M                      0
9   onehotencoder__x1_N                      0
10  onehotencoder__x1_O                      0
11  onehotencoder__x1_P                      0
12  onehotencoder__x1_S                      0
13  onehotencoder__x1_U                      0
14                  SEX                      0
15              MARITAL                      0
16                 FAGE                      0
17               GAINED                      1
18               VISITS                      0
19                 MAGE                      0
20                FEDUC                      1
21                MEDUC                      0
22               TOTALP                      0
23                BDEAD                      0
24                TERMS                      0
25             LOUTCOME                      0
26                WEEKS                      1
27              RACEMOM                      0
28              RACEDAD                      0
29               CIGNUM                      1
30             DRINKNUM                      0
31               ANEMIA                      0
32              CARDIAC                      0
33               ACLUNG                      0
34             DIABETES                      0
35               HERPES                      0
36               HYDRAM                      1
37             HEMOGLOB                      0
38              HYPERCH                      0
39              HYPERPR                      0
40               ECLAMP                      0
41               CERVIX                      0
42              PINFANT                      0
43              PRETERM                      0
44                RENAL                      0
45                RHSEN                      0
46              UTERINE                      0

X_train_ohe_imputed dataframe :

onehotencoder__x0_C    0
onehotencoder__x0_M    0
onehotencoder__x0_N    0
onehotencoder__x0_O    0
onehotencoder__x0_P    0
onehotencoder__x0_S    0
onehotencoder__x0_U    0
onehotencoder__x1_C    0
onehotencoder__x1_M    0
onehotencoder__x1_N    0
onehotencoder__x1_O    0
onehotencoder__x1_P    0
onehotencoder__x1_S    0
onehotencoder__x1_U    0
SEX                    0
MARITAL                0
FAGE                   0
GAINED                 0
VISITS                 0
MAGE                   0
FEDUC                  0
MEDUC                  0
TOTALP                 0
BDEAD                  0
TERMS                  0
LOUTCOME               0
WEEKS                  0
RACEMOM                0
RACEDAD                0
CIGNUM                 0
DRINKNUM               0
ANEMIA                 0
CARDIAC                0
ACLUNG                 0
DIABETES               0
HERPES                 0
HYDRAM                 0
HEMOGLOB               0
HYPERCH                0
HYPERPR                0
ECLAMP                 0
CERVIX                 0
PINFANT                0
PRETERM                0
RENAL                  0
RHSEN                  0
UTERINE                0
dtype: int64

## TASK 6: 
* Given a X_train_ohe_imputed (Pandas dataframe from Task 5) where all the categorical variables are already replaced with numeric values, print a list of top 20 highly correlated variables with respect to the target variable, and save the result as a Pandas dataframe named top20_df with 2 columns {variable,corr_score}. 
* Here, the corr_score between a variable x and the target variable y needs to be computed using the Pearson Correlation Coefficient (PCC). Please note, PCC ranges between -1 to +1. PCC score 0 means no correlation, while value towards +1 and -1 represent positive and negative correlations respectively. For instance, PCC=0.8 and PCC=-0.8 tell similar strength positive and negative correlations between the two subject variables.
* Please do not include BWEIGHT in the top20_df list of top 20 correlated variable list.

In [41]:
from scipy.stats import pearsonr

variable_list = []
corr_score_list = []

#calculate the correlation valu for each variable
for i in X_train_ohe_imputed.columns:
    variable_list.append(i)
    corr, _ = pearsonr(X_train_ohe_imputed[i], y_train)
    corr_score_list.append(corr)    
    

top_df_dic = {'variable':variable_list, 'corr_score':corr_score_list}
top20_df = pd.DataFrame(top_df_dic)
top20_df['Absolute_corr_score'] = abs(top20_df['corr_score'])
top20_df.sort_values(by=['Absolute_corr_score'], ascending=False, inplace=True)
top20_df.drop(['Absolute_corr_score'], axis=1, inplace=True )
top20_df = top20_df.iloc[:20]

top20_df.info()

print(top20_df['variable'].unique())

top20_df.head(20)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20 entries, 26 to 46
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   variable    20 non-null     object
 1   corr_score  20 non-null     float64
dtypes: float64(1), object(1)
memory usage: 480.0+ bytes
['WEEKS' 'GAINED' 'VISITS' 'HYPERPR' 'MARITAL' 'SEX' 'CIGNUM' 'RACEDAD'
 'RACEMOM' 'PRETERM' 'CERVIX' 'MAGE' 'PINFANT' 'ECLAMP' 'MEDUC' 'FAGE'
 'FEDUC' 'HYDRAM' 'HYPERCH' 'UTERINE']

   variable  corr_score
26    WEEKS    0.565254
17   GAINED    0.174466
18   VISITS    0.129247
39  HYPERPR   -0.111375
15  MARITAL   -0.106297
14      SEX   -0.091260
29   CIGNUM   -0.086711
28  RACEDAD   -0.084284
27  RACEMOM   -0.078811
43  PRETERM   -0.075237
41   CERVIX   -0.068751
19     MAGE    0.068550
42  PINFANT    0.065963
40   ECLAMP   -0.065429
21    MEDUC    0.055249
16     FAGE    0.051981
20    FEDUC    0.051537
36   HYDRAM   -0.050019
38  HYPERCH   -0.047094
46  UTERINE   -0.040339

In [42]:
X_train_ohe_imputed['BWEIGHT'] = y_train
corr_df = X_train_ohe_imputed.corr(method='pearson')[('BWEIGHT')]
corr_df = corr_df.to_frame()
X_train_ohe_imputed.drop(['BWEIGHT'], axis=1, inplace=True)
X_train_ohe_imputed.info()

#corr_df['Absolute_corr_score'] = abs(corr_df['corr_score'])
#corr_df.sort_values(by=['Absolute_corr_score'], ascending=False, inplace=True)
#corr_df.drop(['Absolute_corr_score'], axis=1, inplace=True )
corr_df.info()
corr_df.head(47)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76050 entries, 0 to 76049
Data columns (total 47 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   onehotencoder__x0_C  76050 non-null  float64
 1   onehotencoder__x0_M  76050 non-null  float64
 2   onehotencoder__x0_N  76050 non-null  float64
 3   onehotencoder__x0_O  76050 non-null  float64
 4   onehotencoder__x0_P  76050 non-null  float64
 5   onehotencoder__x0_S  76050 non-null  float64
 6   onehotencoder__x0_U  76050 non-null  float64
 7   onehotencoder__x1_C  76050 non-null  float64
 8   onehotencoder__x1_M  76050 non-null  float64
 9   onehotencoder__x1_N  76050 non-null  float64
 10  onehotencoder__x1_O  76050 non-null  float64
 11  onehotencoder__x1_P  76050 non-null  float64
 12  onehotencoder__x1_S  76050 non-null  float64
 13  onehotencoder__x1_U  76050 non-null  float64
 14  SEX                  76050 non-null  float64
 15  MARITAL              76050 non-null  float64
 16  FAGE                 76050 non-null  float64
 17  GAINED               76050 non-null  float64
 18  VISITS               76050 non-null  float64
 19  MAGE                 76050 non-null  float64
 20  FEDUC                76050 non-null  float64
 21  MEDUC                76050 non-null  float64
 22  TOTALP               76050 non-null  float64
 23  BDEAD                76050 non-null  float64
 24  TERMS                76050 non-null  float64
 25  LOUTCOME             76050 non-null  float64
 26  WEEKS                76050 non-null  float64
 27  RACEMOM              76050 non-null  float64
 28  RACEDAD              76050 non-null  float64
 29  CIGNUM               76050 non-null  float64
 30  DRINKNUM             76050 non-null  float64
 31  ANEMIA               76050 non-null  float64
 32  CARDIAC              76050 non-null  float64
 33  ACLUNG               76050 non-null  float64
 34  DIABETES             76050 non-null  float64
 35  HERPES               76050 non-null  float64
 36  HYDRAM               76050 non-null  float64
 37  HEMOGLOB             76050 non-null  float64
 38  HYPERCH              76050 non-null  float64
 39  HYPERPR              76050 non-null  float64
 40  ECLAMP               76050 non-null  float64
 41  CERVIX               76050 non-null  float64
 42  PINFANT              76050 non-null  float64
 43  PRETERM              76050 non-null  float64
 44  RENAL                76050 non-null  float64
 45  RHSEN                76050 non-null  float64
 46  UTERINE              76050 non-null  float64
dtypes: float64(47)
memory usage: 27.3 MB
<class 'pandas.core.frame.DataFrame'>
Index: 48 entries, onehotencoder__x0_C to BWEIGHT
Data columns (total 1 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   BWEIGHT  48 non-null     float64
dtypes: float64(1)
memory usage: 1.8+ KB

                      BWEIGHT
onehotencoder__x0_C -0.000085
onehotencoder__x0_M  0.002062
onehotencoder__x0_N -0.002872
onehotencoder__x0_O  0.005264
onehotencoder__x0_P -0.000648
onehotencoder__x0_S  0.000798
onehotencoder__x0_U  0.004148
onehotencoder__x1_C  0.000511
onehotencoder__x1_M  0.000696
onehotencoder__x1_N -0.006962
onehotencoder__x1_O  0.006191
onehotencoder__x1_P  0.004107
onehotencoder__x1_S  0.008514
onehotencoder__x1_U  0.004371
SEX                  0.001515
MARITAL             -0.001298
FAGE                -0.000429
GAINED              -0.008894
VISITS              -0.005204
MAGE                -0.006278
FEDUC               -0.005683
MEDUC               -0.003474
TOTALP              -0.007463
BDEAD               -0.007951
TERMS               -0.008055
LOUTCOME             0.003080
WEEKS               -0.000945
RACEMOM              0.005348
RACEDAD              0.005357
CIGNUM              -0.000615
DRINKNUM            -0.001095
ANEMIA              -0.003266
CARDIAC              0.011286
ACLUNG              -0.005537
DIABETES            -0.003417
HERPES              -0.006062
HYDRAM              -0.007007
HEMOGLOB            -0.000262
HYPERCH              0.001047
HYPERPR             -0.002619
ECLAMP              -0.000870
CERVIX               0.010087
PINFANT             -0.004799
PRETERM             -0.003569
RENAL                0.002545
RHSEN                0.001851
UTERINE             -0.004468

## TASK 7: 
Given the X_train_ohe_imputed (as Pandas dataframe from task 5) and and top20_df (as Pandas Dataframe from Task 6) having 2 columns {variable_name,corr_score} similar to the one you computed in Task 6:
* Please save as X_train_t20 keeping only the columns listed in the top20_df dataframe.
* Repeat the process for X_test_ohe (obtained from task 4), and save it as X_test_t20.

In [43]:
new_columns = top20_df['variable'].unique()

X_train_t20 = X_train_ohe_imputed[X_train_ohe_imputed.columns[X_train_ohe_imputed.columns.isin(new_columns)]]
X_train_t20.info()

#X_test_ohe - replacing missing values with mean of the columns
X_test_ohe_imputed  = X_test_ohe.copy()
for i in X_test_ohe_imputed.columns:
    mean_val = X_test_ohe_imputed[i].mean()
    X_test_ohe_imputed[i].fillna(value=mean_val, inplace=True)
    

X_test_t20 = X_test_ohe_imputed[X_test_ohe_imputed.columns[X_test_ohe_imputed.columns.isin(new_columns)]]
X_test_t20.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76050 entries, 0 to 76049
Data columns (total 20 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   SEX      76050 non-null  float64
 1   MARITAL  76050 non-null  float64
 2   FAGE     76050 non-null  float64
 3   GAINED   76050 non-null  float64
 4   VISITS   76050 non-null  float64
 5   MAGE     76050 non-null  float64
 6   FEDUC    76050 non-null  float64
 7   MEDUC    76050 non-null  float64
 8   WEEKS    76050 non-null  float64
 9   RACEMOM  76050 non-null  float64
 10  RACEDAD  76050 non-null  float64
 11  CIGNUM   76050 non-null  float64
 12  HYDRAM   76050 non-null  float64
 13  HYPERCH  76050 non-null  float64
 14  HYPERPR  76050 non-null  float64
 15  ECLAMP   76050 non-null  float64
 16  CERVIX   76050 non-null  float64
 17  PINFANT  76050 non-null  float64
 18  PRETERM  76050 non-null  float64
 19  UTERINE  76050 non-null  float64
dtypes: float64(20)
memory usage: 11.6 MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25350 entries, 0 to 25349
Data columns (total 20 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   SEX      25350 non-null  float64
 1   MARITAL  25350 non-null  float64
 2   FAGE     25350 non-null  float64
 3   GAINED   25350 non-null  float64
 4   VISITS   25350 non-null  float64
 5   MAGE     25350 non-null  float64
 6   FEDUC    25350 non-null  float64
 7   MEDUC    25350 non-null  float64
 8   WEEKS    25350 non-null  float64
 9   RACEMOM  25350 non-null  float64
 10  RACEDAD  25350 non-null  float64
 11  CIGNUM   25350 non-null  float64
 12  HYDRAM   25350 non-null  float64
 13  HYPERCH  25350 non-null  float64
 14  HYPERPR  25350 non-null  float64
 15  ECLAMP   25350 non-null  float64
 16  CERVIX   25350 non-null  float64
 17  PINFANT  25350 non-null  float64
 18  PRETERM  25350 non-null  float64
 19  UTERINE  25350 non-null  float64
dtypes: float64(20)
memory usage: 3.9 MB

In [44]:
X_test_t20.head()

,SEX,MARITAL,FAGE,GAINED,VISITS,MAGE,FEDUC,MEDUC,WEEKS,RACEMOM,RACEDAD,CIGNUM,HYDRAM,HYPERCH,HYPERPR,ECLAMP,CERVIX,PINFANT,PRETERM,UTERINE
0,2.0,1.0,30.0,33.0,16.0,29.0,16.0,17.0,39.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2.0,1.0,23.0,20.0,10.0,22.0,12.0,15.0,39.0,2.0,2.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1.0,2.0,24.0,34.0,12.0,21.0,10.0,14.0,38.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2.0,1.0,32.0,16.0,15.0,28.0,12.0,13.0,39.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2.0,1.0,26.0,30.0,7.0,30.0,16.0,16.0,39.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## TASK 8: 
* Apply min-max scaling on the training dataset (X_train_t20 obtained from Task 7). Save the result as X_train_scaled_mm.
* Then scale the test dataset (X_test_t20 obtained from Task 7) based on the metrics you obtain when you scale the training dataset. Save the result as X_test_scaled_mm.
* PLEASE DO NOT SCALE y_train and y_test.

In [48]:
#@TODO: Your code goes here

X_trained_scaled_mm = X_train_t20.copy() 

for i in X_trained_scaled_mm.columns:
    min_value = X_train_t20[i].min() 
    max_value = X_train_t20[i].max() 
    X_trained_scaled_mm[i] = (X_trained_scaled_mm[i] - min_value)/(max_value-min_value)
    
X_trained_scaled_mm.info()


X_test_scaled_mm = X_test_t20.copy() 

for i in X_test_scaled_mm.columns:
    min_value = X_train_t20[i].min() 
    max_value = X_train_t20[i].max() 
    X_test_scaled_mm[i] = (X_test_scaled_mm[i] - min_value)/(max_value-min_value)
    
X_test_scaled_mm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76050 entries, 0 to 76049
Data columns (total 20 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   SEX      76050 non-null  float64
 1   MARITAL  76050 non-null  float64
 2   FAGE     76050 non-null  float64
 3   GAINED   76050 non-null  float64
 4   VISITS   76050 non-null  float64
 5   MAGE     76050 non-null  float64
 6   FEDUC    76050 non-null  float64
 7   MEDUC    76050 non-null  float64
 8   WEEKS    76050 non-null  float64
 9   RACEMOM  76050 non-null  float64
 10  RACEDAD  76050 non-null  float64
 11  CIGNUM   76050 non-null  float64
 12  HYDRAM   76050 non-null  float64
 13  HYPERCH  76050 non-null  float64
 14  HYPERPR  76050 non-null  float64
 15  ECLAMP   76050 non-null  float64
 16  CERVIX   76050 non-null  float64
 17  PINFANT  76050 non-null  float64
 18  PRETERM  76050 non-null  float64
 19  UTERINE  76050 non-null  float64
dtypes: float64(20)
memory usage: 11.6 MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25350 entries, 0 to 25349
Data columns (total 20 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   SEX      25350 non-null  float64
 1   MARITAL  25350 non-null  float64
 2   FAGE     25350 non-null  float64
 3   GAINED   25350 non-null  float64
 4   VISITS   25350 non-null  float64
 5   MAGE     25350 non-null  float64
 6   FEDUC    25350 non-null  float64
 7   MEDUC    25350 non-null  float64
 8   WEEKS    25350 non-null  float64
 9   RACEMOM  25350 non-null  float64
 10  RACEDAD  25350 non-null  float64
 11  CIGNUM   25350 non-null  float64
 12  HYDRAM   25350 non-null  float64
 13  HYPERCH  25350 non-null  float64
 14  HYPERPR  25350 non-null  float64
 15  ECLAMP   25350 non-null  float64
 16  CERVIX   25350 non-null  float64
 17  PINFANT  25350 non-null  float64
 18  PRETERM  25350 non-null  float64
 19  UTERINE  25350 non-null  float64
dtypes: float64(20)
memory usage: 3.9 MB

In [49]:
X_trained_scaled_mm.head()

,SEX,MARITAL,FAGE,GAINED,VISITS,MAGE,FEDUC,MEDUC,WEEKS,RACEMOM,RACEDAD,CIGNUM,HYDRAM,HYPERCH,HYPERPR,ECLAMP,CERVIX,PINFANT,PRETERM,UTERINE
0,0.000,0.0,0.366667,0.510204,0.326531,0.475,0.705882,0.764706,0.740741,0.125,0.111111,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,0.125,1.0,0.150000,0.510204,0.265306,0.175,0.705882,0.882353,0.851852,0.250,0.222222,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.000,0.0,0.200000,0.387755,0.224490,0.200,0.705882,0.764706,0.814815,0.125,0.111111,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,0.000,1.0,0.133333,0.204082,0.204082,0.150,0.705882,0.705882,0.814815,0.125,0.111111,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.125,0.0,0.350000,0.306122,0.265306,0.425,0.941176,1.000000,0.777778,0.125,0.111111,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [50]:
X_test_scaled_mm.head()

,SEX,MARITAL,FAGE,GAINED,VISITS,MAGE,FEDUC,MEDUC,WEEKS,RACEMOM,RACEDAD,CIGNUM,HYDRAM,HYPERCH,HYPERPR,ECLAMP,CERVIX,PINFANT,PRETERM,UTERINE
0,0.125,0.0,0.266667,0.336735,0.326531,0.400,0.941176,1.000000,0.777778,0.125,0.111111,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.125,0.0,0.150000,0.204082,0.204082,0.225,0.705882,0.882353,0.777778,0.250,0.222222,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.000,1.0,0.166667,0.346939,0.244898,0.200,0.588235,0.823529,0.740741,0.250,0.222222,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.125,0.0,0.300000,0.163265,0.306122,0.375,0.705882,0.764706,0.777778,0.125,0.111111,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.125,0.0,0.200000,0.306122,0.142857,0.425,0.941176,0.941176,0.777778,0.125,0.111111,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## TASK 9: 
* Apply standardization (i.e., normalization) scaling on the training dataset (X_train_t20 obtained from Task 7). Save the result as X_train_scaled_std.
* Then scale the test dataset (X_test_t20 obtained from Task 7) based on the metrics you obtain when you scale the training dataset. Save the result as X_test_scaled_std.
* PLEASE DO NOT SCALE y_train and y_test.

In [53]:
#@TODO: Your code goes here
X_train_scaled_std = X_train_t20.copy() 

for i in X_train_scaled_std.columns:
    mean = X_train_t20[i].mean() 
    std = X_train_t20[i].std()
    X_train_scaled_std[i] = (X_train_scaled_std[i] - mean)/std
    
X_train_scaled_std.info()




X_test_scaled_std = X_test_t20.copy() 

for i in X_test_scaled_std.columns:
    mean = X_train_t20[i].mean() 
    std = X_train_t20[i].std()
    X_test_scaled_std[i] = (X_test_scaled_std[i] - mean)/std    
X_test_scaled_std.info()
X_test_scaled_std.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76050 entries, 0 to 76049
Data columns (total 20 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   SEX      76050 non-null  float64
 1   MARITAL  76050 non-null  float64
 2   FAGE     76050 non-null  float64
 3   GAINED   76050 non-null  float64
 4   VISITS   76050 non-null  float64
 5   MAGE     76050 non-null  float64
 6   FEDUC    76050 non-null  float64
 7   MEDUC    76050 non-null  float64
 8   WEEKS    76050 non-null  float64
 9   RACEMOM  76050 non-null  float64
 10  RACEDAD  76050 non-null  float64
 11  CIGNUM   76050 non-null  float64
 12  HYDRAM   76050 non-null  float64
 13  HYPERCH  76050 non-null  float64
 14  HYPERPR  76050 non-null  float64
 15  ECLAMP   76050 non-null  float64
 16  CERVIX   76050 non-null  float64
 17  PINFANT  76050 non-null  float64
 18  PRETERM  76050 non-null  float64
 19  UTERINE  76050 non-null  float64
dtypes: float64(20)
memory usage: 11.6 MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25350 entries, 0 to 25349
Data columns (total 20 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   SEX      25350 non-null  float64
 1   MARITAL  25350 non-null  float64
 2   FAGE     25350 non-null  float64
 3   GAINED   25350 non-null  float64
 4   VISITS   25350 non-null  float64
 5   MAGE     25350 non-null  float64
 6   FEDUC    25350 non-null  float64
 7   MEDUC    25350 non-null  float64
 8   WEEKS    25350 non-null  float64
 9   RACEMOM  25350 non-null  float64
 10  RACEDAD  25350 non-null  float64
 11  CIGNUM   25350 non-null  float64
 12  HYDRAM   25350 non-null  float64
 13  HYPERCH  25350 non-null  float64
 14  HYPERPR  25350 non-null  float64
 15  ECLAMP   25350 non-null  float64
 16  CERVIX   25350 non-null  float64
 17  PINFANT  25350 non-null  float64
 18  PRETERM  25350 non-null  float64
 19  UTERINE  25350 non-null  float64
dtypes: float64(20)
memory usage: 3.9 MB

,SEX,MARITAL,FAGE,GAINED,VISITS,MAGE,FEDUC,MEDUC,WEEKS,RACEMOM,RACEDAD,CIGNUM,HYDRAM,HYPERCH,HYPERPR,ECLAMP,CERVIX,PINFANT,PRETERM,UTERINE
0,1.025947,-0.660619,-0.023970,0.202532,0.951579,0.211939,1.051499,1.279033,0.105722,-0.338691,-0.352701,-0.24368,-0.123088,-0.118321,-0.231045,-0.060789,-0.061976,-0.076719,-0.094419,-0.05823
1,1.025947,-0.660619,-1.057125,-0.753834,-0.653742,-0.962228,-0.315858,0.596177,0.105722,0.426965,0.446718,-0.24368,-0.123088,8.451487,-0.231045,-0.060789,-0.061976,-0.076719,-0.094419,-0.05823
2,-0.971832,1.513712,-0.909531,0.276098,-0.118635,-1.129966,-0.999537,0.254749,-0.293111,0.426965,0.446718,-0.24368,-0.123088,-0.118321,-0.231045,-0.060789,-0.061976,-0.076719,-0.094419,-0.05823
3,1.025947,-0.660619,0.271217,-1.048100,0.684026,0.044201,-0.315858,-0.086679,0.105722,-0.338691,-0.352701,-0.24368,-0.123088,-0.118321,-0.231045,-0.060789,-0.061976,-0.076719,-0.094419,-0.05823
4,1.025947,-0.660619,-0.614344,-0.018168,-1.456402,0.379677,1.051499,0.937605,0.105722,-0.338691,-0.352701,-0.24368,-0.123088,-0.118321,-0.231045,-0.060789,-0.061976,-0.076719,-0.094419,-0.05823

## TASK 10: 
Given the (X_train_scaled_std, y_train) pairs denoting input matrix and output vector respectively: complete the three function definitions and demonstrate the functionalities of each by calling them with appropriate arguments as instructed below:
* **linear_regression_closed_form_training** : It fits a linear regression model using the closed-form solution to obtain the coefficients, beta's, as a numpy array of m+1 values (Please recall class lecture), where *m* is the number of variables kept in X_train (the first argument to the function). Please measure the cpu_time needed during the training step. cpu_time is not equal to the wall_time. So, use time.perf_counter() for an accurate measurement. Documentation on this function can be found here: https://docs.python.org/3/library/time.html . Finally, the function returns betas (i.e., the m+1 beta values) and the  cpu_time.
* **linear_regression_closed_form_predict**: It takes a list of m+1 beta values (i.e., betas returned from the corresponding training function, and X_test (containing test samples each having *m* input variables). Now, using the provided beta values, predict each of the test samples provided, and let's name your prediction "y_pred". Return y_pred from the function.
* **RMSE**: It takes two lists: y_test, y_pred, where the first list represents ground truth (i.e., actual) target values for the given samples, and the second list represents a corresponding predicted values for exactly same number of samples in y_test. Compute and return the Root Mean Squared Error (RMSE) of the prediction. 

* PLEASE DO NOT USE ANY LIBRARY FUNCTION THAT DOES THE LINEAR REGRESSION.
* Now, call linear_regression_closed_form_training() function providing X_train_scaled_std, y_train obtained from Task 9, and save the returned results as betas_closed_form,cpu_time_closed_form.
* Print betas_closed_form, cpu_time_closed_form
* Call linear_regression_closed_form_predict() function providing betas_closed_form,X_test_scaled_std obtained in Task 9. Save the returned result as y_pred.
* Call RMSE() function providing y_test and y_pred. Save returned result as rmse_closed_form.
* Print rmse_closed_form.

In [55]:
import numpy as np
from numpy.linalg import inv
from time import perf_counter

def linear_regression_closed_form_training(X_train, y_train):
    cpu_time = 0
    betas = []
    
    starting_time = perf_counter()
    
    betas = np.dot(np.linalg.inv(np.dot(X_train.T, X_train)), np.dot(X_train.T, y_train)) 
    
    ending_time = perf_counter()
    cpu_time = ending_time - starting_time
    
    return betas,cpu_time


def linear_regression_closed_form_predict(betas, X_test):
    y_pred = []
    
    y_pred = np.dot(X_test, betas)
       
    return y_pred


def RMSE(y_test, y_pred):
    rmse = -1   
    sum_val = 0
     
    n = len(y_test)
    for i in range(len(y_test)):
        sum_val  = sum_val + (y_test[i]-y_pred[i])**2
    rmse = np.sqrt(sum_val/n)
       
    return rmse

In [56]:
X_train_scaled_std1 = np.c_[np.ones(len(X_train_scaled_std),dtype='int64'),X_train_scaled_std]
betas_closed_form, cpu_time_closed_form = linear_regression_closed_form_training(X_train_scaled_std1, y_train)
print('cpu_time ',cpu_time_closed_form)

X_test_scaled_std1 = np.c_[np.ones(len(X_test_scaled_std),dtype='int64'),X_test_scaled_std]
y_pred = linear_regression_closed_form_predict(betas_closed_form, X_test_scaled_std1)
y_pred_closed = y_pred

cpu_time  0.004721000000017739

In [57]:
#rmse formula 
rmse_closed_form = RMSE(y_test.to_numpy(), y_pred_closed)
print( rmse_closed_form)

1.043524730021417

## TASK 11: 
Given the (X_train_scaled_std, y_train) pairs denoting input matrix and output vector respectively: complete the three function definitions and demonstrate the functionalities of each by calling them with appropriate arguments as instructed below:
* **linear_regression_gd_batch_training** : It fits a linear regression model using the batch gradient descent algorithm to obtain the coefficients, beta's, as a numpy array of m+1 values, where *m* is the number of variables kept in X_train (the first argument to the function). Please use the alpha (i.e, the learning rate) and nEpoch (number of epochs) parameters in your implementation of the gradient descent algorithm. Please measure the cpu_time needed during the training step. cpu_time is not equal to the wall_time. So, use time.perf_counter() for an accurate measurement. Documentation on this function can be found here: https://docs.python.org/3/library/time.html . Finally, the function returns betas (i.e., the m+1 beta values) and the  cpu_time.
* **linear_regression_gd_batch_predict**: It takes a list of m+1 beta values (i.e., betas returned from the corresponding training function, and X_test (containing test samples each having *m* input variables). Now, using the provided beta values, predict each of the test samples provided, and let's name your prediction "y_pred". Return y_pred from the function. 

* PLEASE DO NOT USE ANY LIBRARY FUNCTION THAT DOES THE LINEAR REGRESSION.
* Now, call linear_regression_gd_batch_training() function providing X_train_scaled_std, y_train obtained from Task 9, and alpha=0.01,nEpoch=1000, and save the returned results as betas_batch,cpu_time_batch.
* Print betas_batch, cpu_time_batch
* Call linear_regression_gd_batch_predict() function providing betas_batch,X_test_scaled_std obtained in Task 9. Save the returned result as y_pred.
* Call RMSE() function providing y_test and y_pred. Save returned result as rmse_batch.
* Print rmse_batch.

In [73]:
from time import perf_counter
def cost_function(X, Y, betas):
    n = len(Y)
    J = (np.sum((X.dot(betas) - Y) ** 2))/(2 * n) 
    return J


def linear_regression_gd_batch_training(X_train,y_train, alpha, nEpoch):
    import random
    random.seed(554433)
    from time import perf_counter
    import numpy as np
    betas = []
    cpu_time = 0
    
    
    starting_time = perf_counter()
    
    betas = np.zeros(X_train.shape[1])
    
    
    betas = np.zeros(X_train.shape[1])

    for i in range(nEpoch):
        y_pred = X_train.dot(betas)
        diff = y_pred - y_train
        gradient = X_train.T.dot(diff) / len(y_train)
        
        betas = betas - alpha * gradient
        
        cost = cost_function(X_train, y_train, betas)
        
    ending_time = perf_counter()
    cpu_time = ending_time - starting_time
    print(y_pred)

    return betas, cpu_time
    
    #alpha=0.01,nEpoch=1000

In [74]:
betas_batch, cpu_time_batch = linear_regression_gd_batch_training(X_train_scaled_std1, y_train, alpha=0.01,nEpoch=1000)

[8.62184809 7.75994344 7.47447071 ... 7.63079534 7.36824371 7.25999961]

In [75]:
print('final betas : ',betas_batch)
print('cpu_time : ',cpu_time_batch)

final betas :  [ 7.25668457 -0.12962493 -0.07673593  0.01409182  0.16438285  0.03421767
  0.09749111 -0.01579987 -0.01549879  0.71491597 -0.04526138 -0.05814852
 -0.09270047 -0.04401612 -0.02636977 -0.08270012 -0.03916627 -0.02743378
  0.07238309 -0.03883247 -0.01920212]
cpu_time :  3.1475725999999895

In [76]:
def linear_regression_gd_batch_predict(betas,X_test):
    y_pred = []
    y_pred = np.dot(X_test,betas)
    return y_pred

In [77]:
y_pred = linear_regression_gd_batch_predict(betas_batch, X_test_scaled_std1)

In [78]:
rmse_batch = RMSE(y_test.to_numpy(), y_pred_gbatch)
print( rmse_batch)

1.0435331638360321

## TASK 12:
Given the (X_train_scaled_std, y_train) pairs denoting input matrix and output vector respectively: complete the three function definitions and demonstrate the functionalities of each by calling them with appropriate arguments as instructed below:
* **linear_regression_gd_stochastic_training** : It fits a linear regression model using the stochastic gradient descent algorithm to obtain the coefficients, beta's, as a numpy array of m+1 values, where *m* is the number of variables kept in X_train (the first argument to the function). Please use the alpha (i.e, the learning rate), nEpoch (number of epochs), nIteration (number of iterations) parameters in your implementation of the gradient descent algorithm. Please measure the cpu_time needed during the training step. cpu_time is not equal to the wall_time. So, use time.perf_counter() for an accurate measurement. Documentation on this function can be found here: https://docs.python.org/3/library/time.html . Finally, the function returns betas (i.e., the m+1 beta values) and the  cpu_time.
* **linear_regression_gd_stochastic_predict**: It takes a list of m+1 beta values (i.e., betas returned from the corresponding training function, and X_test (containing test samples each having *m* input variables). Now, using the provided beta values, predict each of the test samples provided, and let's name your prediction "y_pred". Return y_pred from the function. 

* PLEASE DO NOT USE ANY LIBRARY FUNCTION THAT DOES THE LINEAR REGRESSION.
* Now, call linear_regression_gd_stochastic_training() function providing X_train_scaled_std, y_train obtained from Task 9, and alpha=0.01,nEpoch=50, nIteration=100 , and save the returned results as betas_stochastic,cpu_time_stochastic.
* Print betas_stochastic, cpu_time_stochastic
* Call linear_regression_gd_stochastic_predict() function providing betas_stochastic,X_test_scaled_std obtained in Task 9. Save the returned result as y_pred.
* Call RMSE() function providing y_test and y_pred. Save returned result as rmse_stochastic.
* Print rmse_stochastic.

In [70]:
def cost_function(X, Y, betas):
    n = len(Y)
    J = (np.sum((X.dot(betas) - Y) ** 2))/(2 * n) 
    return J

In [85]:
def linear_regression_gd_stochastic_training(X_train,y_train,alpha,nEpoch,nIteration):
    import random
    from time import perf_counter
    import numpy as np
    random.seed(554433)
    betas = []
    cpu_time = 0
    
    starting_time = perf_counter()  
    betas = np.zeros(X_train.shape[1])
         
    for num in range(nIteration):
        j = random.randint(0, len(X_train))
        y_pred = X_train[j].dot(betas)
        difference = y_pred - y_train.to_numpy()[j]

        gradient = X_train[j].T.dot(difference) / len(X_train)
        betas = betas - alpha * gradient
        
        cost = cost_function(X_train, y_train, betas)
        
    ending_time = perf_counter()
    cpu_time = ending_time - starting_time
    
    return betas, cpu_time

In [86]:
betas_stochastic, cpu_time_stochastic = linear_regression_gd_stochastic_training(X_train_scaled_std1, y_train, alpha=0.01,nEpoch=50,nIteration=100)

In [87]:
#@TODO: Your code goes here
def linear_regression_gd_stochastic_predict(betas, X_test):
    y_pred = []
    y_pred = np.dot(X_test,betas)
    return y_pred

In [88]:
#@TODO: Your code goes here
y_pred = linear_regression_gd_stochastic_predict(betas_stochastic, X_test_scaled_std1)
rmse_stochastic = RMSE(y_test.to_numpy(), y_pred)
print( rmse_stochastic)

7.381551956458342

## Task 13: 
Given the (X_train_scaled_std, y_train) pairs denoting input matrix and output vector respectively: complete the three function definitions and demonstrate the functionalities of each by calling them with appropriate arguments as instructed below:
* **linear_regression_gd_minibatch_training** : It fits a linear regression model using the minibatch gradient descent algorithm to obtain the coefficients, beta's, as a numpy array of m+1 values, where *m* is the number of variables kept in X_train (the first argument to the function). Please use the alpha (i.e, the learning rate), nEpoch (number of epochs), nIteration (number of iterations), and batch_size parameters in your implementation of the gradient descent algorithm. Please measure the cpu_time needed during the training step. cpu_time is not equal to the wall_time. So, use time.perf_counter() for an accurate measurement. Documentation on this function can be found here: https://docs.python.org/3/library/time.html . Finally, the function returns betas (i.e., the m+1 beta values) and the  cpu_time.
* **linear_regression_gd_minibatch_predict**: It takes a list of m+1 beta values (i.e., betas returned from the corresponding training function, and X_test (containing test samples each having *m* input variables). Now, using the provided beta values, predict each of the test samples provided, and let's name your prediction "y_pred". Return y_pred from the function. 

* PLEASE DO NOT USE ANY LIBRARY FUNCTION THAT DOES THE LINEAR REGRESSION.
* Now, call linear_regression_gd_minibatch_training() function providing X_train_scaled_std, y_train obtained from Task 9, and alpha=0.001,nEpoch=50, nIteration=1000,batch_size=32, and save the returned results as betas_minibatch,cpu_time_minibatch.
* Print betas_minibatch, cpu_time_minibatch
* Call linear_regression_gd_minibatch_predict() function providing betas_minibatch,X_test_scaled_std obtained in Task 9. Save the returned result as y_pred.
* Call RMSE() function providing y_test and y_pred. Save returned result as rmse_minibatch.
* Print rmse_minibatch.

In [89]:
def cost_function(X, Y, betas):
    n = len(Y)
    J = (np.sum((X.dot(betas) - Y) ** 2))/(2 * n) 
    return J

In [92]:
def linear_regression_gd_minibatch_training(X_train,y_train,alpha,nEpoch, nIteration, batch_size):
    import random
    from time import perf_counter
    import numpy as np
    random.seed(554433)

    betas = []
    cpu_time = 0
      
    starting_time = perf_counter()  
    betas = np.zeros(X_train.shape[1])
    
    n = len(X_train)
    
    for i in range(nEpoch):
        ind_val = random.randint(0, len(X_train)-batch_size)
        X_train_mb = X_train[ind_val:ind_val+batch_size]
        y_train_mb = y_train[ind_val:ind_val+batch_size]
        
        for j in range(nIteration):
            y_pred = X_train_mb.dot(betas)
            gradient = X_train_mb.T.dot(y_pred - y_train_mb.to_numpy()) / n 

            betas = betas - alpha * gradient

            cost = cost_function(X_train_mb, y_train_mb, betas)

    ending_time = perf_counter()
    cpu_time = ending_time - starting_time
    
      
    return betas,cpu_time

In [93]:
betas_minibatch, cpu_time_minibatch = linear_regression_gd_minibatch_training(X_train_scaled_std1, y_train, alpha=0.01,nEpoch=50,nIteration=1000, batch_size=32)

In [94]:
def linear_regression_gd_minibatch_predict(betas, X_test):
    y_pred = []
    y_pred = np.dot(X_test,betas)
    return y_pred

In [96]:
y_pred = linear_regression_gd_minibatch_predict(betas_minibatch, X_test_scaled_std1)
rmse_minibatch = RMSE(y_test.to_numpy(), y_pred)
print( rmse_minibatch)

6.011315609558118

## Task 14:
Given the 4 sets of results from the 4 experiments (from Tasks 10, 11, 12, 13) with closed form solution, batch gradient descent, stochastic gradient descent and mini-batch gradient descent, print a string from the set {"closed-form", "batch-GD", "stochastic-GD", "minibatch-GD"} that demonstrated the best predictive performance in terms of RMSE.

In [98]:
print({rmse_closed_form,rmse_batch,rmse_stochastic,rmse_minibatch})
print('The least RMSE is for the closed form linear regression with the rmse value of ', rmse_closed_form)

{6.011315609558118, 1.043524730021417, 1.0435331638360321, 7.381551956458342}
The least RMSE is for the closed form linear regression with the rmse value of  1.043524730021417

## Task 15: 
Given the 4 sets of results from the 4 experiments (from Tasks 10, 11, 12, 13) with closed form solution, batch gradient descent, stochastic gradient descent and mini-batch gradient descent, print a string from the set {"closed-form", "batch-GD", "stochastic-GD", "minibatch-GD"} that demonstrated the least training cpu time.

In [99]:
print({cpu_time_closed_form,cpu_time_batch,cpu_time_stochastic,cpu_time_minibatch})
print('The least CPU time is for the closed form linear regression with the cpu time value of ', cpu_time_closed_form)

{0.004721000000017739, 0.14628190000007635, 3.1475725999999895, 11.672495399999889}
The least CPU time is for the closed form linear regression with the cpu time value of  0.004721000000017739

## Task 16: 
Given the (X_train_scaled_std, y_train) pairs denoting input matrix and output vector respectively, 
* call your implementation of Task 12: stochastic gradient descent based linear regression for each of these learning rates: {0.0001, 0.001, 0.05, 0.01, 0.1, 1.0}
    * Please use the nIteration (number of iterations), nEpoch (number of epoch) parameters in your implementation of the gradient descent algorithm.

* For each of the linear regression model, using the computed beta values, predict the test samples provided in the "X_test_scaled_std" argument, and let's name your prediction "y_pred".
* Compute Root Mean Squared Error (RMSE) of your prediction using the RMSE() function you defined in Task 10.
* Finally, print the learning rate that shows the best test performance, and also print as a pandas dataframe named summary with 2 columns: {learning_rate, test_RMSE} containing RMSE's of the 6 linear regression models. Also, print the best performing learning rate.
* PLEASE DO NOT USE ANY LIBRARY FUNCTION THAT DOES THE LINEAR REGRESSION.

In [103]:
## YOUR CODE HERE ###

#@TODO: Your code goes here
aplha_val = []
rmse_val = []

for alpha_value in [0.0001, 0.001, 0.05, 0.01, 0.1, 1.0]:
    aplha_val.append(alpha_value)
    betas_stochastic, cpu_time_stochastic = linear_regression_gd_stochastic_training(X_train_scaled_std1, y_train, alpha=alpha_value,nEpoch=50,nIteration=100)
    y_pred = linear_regression_gd_stochastic_predict(betas_stochastic, X_test_scaled_std1)
    y_pred_sg = y_pred
    
    rmse_stochastic = RMSE(y_test.to_numpy(), y_pred_sg)
    #print(rmse_stochastic)
    rmse_val.append(rmse_stochastic)
    print('Stochastic gradient descent finished for the alpha value : ',alpha_value)
    
    
test_sg_dic = {'learning_rate': aplha_val, 'test_rmse': rmse_val}
test_sg_df = pd.DataFrame.from_dict(test_sg_dic)

Stochastic gradient descent finished for the alpha value :  0.0001
Stochastic gradient descent finished for the alpha value :  0.001
Stochastic gradient descent finished for the alpha value :  0.05
Stochastic gradient descent finished for the alpha value :  0.01
Stochastic gradient descent finished for the alpha value :  0.1
Stochastic gradient descent finished for the alpha value :  1.0

In [106]:
test_sg_df.info()
test_sg_df.head(6)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   learning_rate  6 non-null      float64
 1   test_rmse      6 non-null      float64
dtypes: float64(2)
memory usage: 224.0 bytes

   learning_rate  test_rmse
0         0.0001   7.381647
1         0.0010   7.381638
2         0.0500   7.381170
3         0.0100   7.381552
4         0.1000   7.380691
5         1.0000   7.372093

In [108]:
print('best learning rate : ',test_sg_df[test_sg_df['test_rmse']==test_sg_df['test_rmse'].min()]['learning_rate'].to_string(index=False))

best learning rate :  1.0

## Task 17:
* Utilizing the best trained linear regression model (so far), predict the target for each of the samples in the judge_dataset.
    * I believe you will not forget to do the following before call in the prediction algorithm:
        - Save the ID values of the judge dataset into ID_judge and drop it from the judge dataframe.
        - Perform onehot encoding using the same encoder you used to encode X_test (Task 4). 
        - keep only the same top 20 variables as you did in Task 7. 
        - scale the input variables based on the same metrics you used to scale the training dataset (Task 9). 
    * Now, call the prediction function of that model to obtain y_pred.
    * Prepare and print as a pandas dataframe having columns: {ID, BWEIGHT}, where ID will the ID of the judge sample, and BWEIGHT is the corresponding y_pred value from your model prediction.
* PLEASE DO NOT USE ANY LIBRARY FUNCTION THAT DOES THE LINEAR REGRESSION.

In [113]:
## YOUR CODE HERE ###
judge_dataset.info()
judge_dataset.head()

ID_judge = judge_dataset.loc[:,'ID'].to_frame()

judge_dataset = judge_dataset.drop('ID', axis=1)
judge_dataset_ohe = pd.DataFrame(column_trans.fit_transform(judge_dataset),columns=column_trans.get_feature_names())


judge_dataset_ohe_imputed  = judge_dataset_ohe.copy()
for i in judge_dataset_ohe_imputed.columns:
    values = judge_dataset_ohe_imputed[i].mean()
    judge_dataset_ohe_imputed[i].fillna(value=values, inplace=True)
    
new_columns = top20_df['variable'].unique()
judge_top_20 = judge_dataset_ohe[judge_dataset_ohe.columns[judge_dataset_ohe.columns.isin(new_columns)]]
judge_scaled_std = judge_top_20.copy() 

for i in judge_scaled_std.columns:
    mean = X_train_t20[i].mean() 
    std = X_train_t20[i].std()
    judge_scaled_std[i] = (judge_scaled_std[i] - mean)/std
    
judge_scaled_std.info()
judge_scaled_std.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 36 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID        2000 non-null   int64
 1   SEX       2000 non-null   int64
 2   MARITAL   2000 non-null   int64
 3   FAGE      2000 non-null   int64
 4   GAINED    2000 non-null   int64
 5   VISITS    2000 non-null   int64
 6   MAGE      2000 non-null   int64
 7   FEDUC     2000 non-null   int64
 8   MEDUC     2000 non-null   int64
 9   TOTALP    2000 non-null   int64
 10  BDEAD     2000 non-null   int64
 11  TERMS     2000 non-null   int64
 12  LOUTCOME  2000 non-null   int64
 13  WEEKS     2000 non-null   int64
 14  RACEMOM   2000 non-null   int64
 15  RACEDAD   2000 non-null   int64
 16  HISPMOM   2000 non-null   object
 17  HISPDAD   2000 non-null   object
 18  CIGNUM    2000 non-null   int64
 19  DRINKNUM  2000 non-null   int64
 20  ANEMIA    2000 non-null   int64
 21  CARDIAC   2000 non-null   int64
 22  ACLUNG    2000 non-null   int64
 23  DIABETES  2000 non-null   int64
 24  HERPES    2000 non-null   int64
 25  HYDRAM    2000 non-null   int64
 26  HEMOGLOB  2000 non-null   int64
 27  HYPERCH   2000 non-null   int64
 28  HYPERPR   2000 non-null   int64
 29  ECLAMP    2000 non-null   int64
 30  CERVIX    2000 non-null   int64
 31  PINFANT   2000 non-null   int64
 32  PRETERM   2000 non-null   int64
 33  RENAL     2000 non-null   int64
 34  RHSEN     2000 non-null   int64
 35  UTERINE   2000 non-null   int64
dtypes: int64(34), object(2)
memory usage: 562.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 20 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   SEX      2000 non-null   float64
 1   MARITAL  2000 non-null   float64
 2   FAGE     2000 non-null   float64
 3   GAINED   2000 non-null   float64
 4   VISITS   2000 non-null   float64
 5   MAGE     2000 non-null   float64
 6   FEDUC    2000 non-null   float64
 7   MEDUC    2000 non-null   float64
 8   WEEKS    2000 non-null   float64
 9   RACEMOM  2000 non-null   float64
 10  RACEDAD  2000 non-null   float64
 11  CIGNUM   2000 non-null   float64
 12  HYDRAM   2000 non-null   float64
 13  HYPERCH  2000 non-null   float64
 14  HYPERPR  2000 non-null   float64
 15  ECLAMP   2000 non-null   float64
 16  CERVIX   2000 non-null   float64
 17  PINFANT  2000 non-null   float64
 18  PRETERM  2000 non-null   float64
 19  UTERINE  2000 non-null   float64
dtypes: float64(20)
memory usage: 312.6 KB

,SEX,MARITAL,FAGE,GAINED,VISITS,MAGE,FEDUC,MEDUC,WEEKS,RACEMOM,RACEDAD,CIGNUM,HYDRAM,HYPERCH,HYPERPR,ECLAMP,CERVIX,PINFANT,PRETERM,UTERINE
0,-0.971832,-0.660619,-0.023970,2.924496,-0.386188,-0.291275,0.367820,0.937605,-1.090777,-0.338691,-0.352701,-0.24368,-0.123088,-0.118321,-0.231045,-0.060789,-0.061976,-0.076719,-0.094419,-0.05823
1,1.025947,1.513712,-1.352312,0.423232,0.684026,-1.633180,-1.341376,-0.428107,0.903389,1.192621,1.246136,-0.24368,-0.123088,-0.118321,-0.231045,-0.060789,-0.061976,-0.076719,-0.094419,-0.05823
2,1.025947,-0.660619,-1.204718,-0.900967,-0.653742,-0.459013,-0.315858,-0.428107,0.105722,-0.338691,-0.352701,6.43377,-0.123088,-0.118321,-0.231045,-0.060789,-0.061976,-0.076719,-0.094419,-0.05823
3,1.025947,-0.660619,-0.909531,-0.386001,-0.653742,-0.962228,-0.315858,-0.769535,0.105722,-0.338691,-0.352701,-0.24368,-0.123088,-0.118321,-0.231045,-0.060789,-0.061976,-0.076719,-0.094419,-0.05823
4,1.025947,-0.660619,-0.909531,0.570365,0.684026,-0.291275,-0.315858,-0.428107,-0.293111,-0.338691,-0.352701,-0.24368,-0.123088,-0.118321,4.328106,-0.060789,-0.061976,-0.076719,-0.094419,-0.05823

In [114]:
judge_scaled_std1 = np.c_[np.ones(len(judge_scaled_std),dtype='int64'), judge_scaled_std]
y_pred = linear_regression_closed_form_predict(betas_closed_form, judge_scaled_std1)

id_list = list(ID_judge['ID'].to_numpy())
y_pred_list = list(y_pred)

judge_result = pd.DataFrame({'ID':id_list, 'BWEIGHT':y_pred_list})
judge_result.info()
judge_result.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   ID       2000 non-null   int64
 1   BWEIGHT  2000 non-null   float64
dtypes: float64(1), int64(1)
memory usage: 31.4 KB

   ID   BWEIGHT
0   1  7.159180
1   2  7.521792
2   3  6.504583
3   4  7.163844
4   5  6.768008

In [115]:
judge_result.to_csv('Judge_Result.csv', index=False)

# Graduate Students only
## Task 18:
Bring your best model and submit your solution at https://www.kaggle.com/c/birth-weight-prediction
Submit multiple entries. Demonstrate your effort by pushing yourself to improve your own score or beat other submissions (if any available) until the deadline and document your scores and list what changes you made in your submitted solution.